language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
cache:
  directories:
    - node_modules
script:
  - npm test
after_success: nyc npm test
notifications:
  email:       false